/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/IHUzeoVOCDN
 */


export function Component() {
  return (
    <div className="bg-gray-50/50 dark:bg-gray-950/50">
      <div className="container grid max-w-3xl gap-6 px-4 py-12 md:gap-8 md:px-6 lg:py-16">
        <div className="flex flex-col gap-2">
          <h3 className="text-2xl font-bold tracking-tighter sm:text-3xl">Getting Started</h3>
          <p className="max-w-[500px] text-gray-500 md:text-base/relaxed lg:text-xl/relaxed xl:text-base/relaxed dark:text-gray-400">
            Learn how to get up and running with our platform in no time.
          </p>
        </div>
        <div className="mx-auto grid grid-cols-1 items-stretch gap-6 sm:grid-cols-2">
          <div className="flex flex-row items-center gap-4 p-4 border border-slate-200 rounded-lg bg-gray-100 md:gap-8 md:p-6 dark:bg-gray-800 dark:border-slate-800">
            <div className="flex flex-col gap-1.5">
              <h4 className="text-lg font-semibold">Quick Start</h4>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                The fastest way to get started with our platform.
              </p>
            </div>
            <img
              alt="Logo"
              className="rounded-full"
              height="40"
              src="/placeholder.svg"
              style={{
                aspectRatio: "40/40",
                objectFit: "cover",
              }}
              width="40"
            />
          </div>
          <div className="flex flex-row items-center gap-4 p-4 border border-slate-200 rounded-lg bg-gray-100 md:gap-8 md:p-6 dark:bg-gray-800 dark:border-slate-800">
            <div className="flex flex-col gap-1.5">
              <h4 className="text-lg font-semibold">Documentation</h4>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Dive deep with our comprehensive documentation.
              </p>
            </div>
            <img
              alt="Logo"
              className="rounded-full"
              height="40"
              src="/placeholder.svg"
              style={{
                aspectRatio: "40/40",
                objectFit: "cover",
              }}
              width="40"
            />
          </div>
          <div className="flex flex-row items-center gap-4 p-4 border border-slate-200 rounded-lg bg-gray-100 md:gap-8 md:p-6 dark:bg-gray-800 dark:border-slate-800">
            <div className="flex flex-col gap-1.5">
              <h4 className="text-lg font-semibold">Community</h4>
              <p className="text-sm text-gray-500 dark:text-gray-400">Join the community and meet other users.</p>
            </div>
            <img
              alt="Logo"
              className="rounded-full"
              height="40"
              src="/placeholder.svg"
              style={{
                aspectRatio: "40/40",
                objectFit: "cover",
              }}
              width="40"
            />
          </div>
        </div>
      </div>
    </div>
  )
}
